version: '3'

services:
  backend:
    image: anno-1800-explorer-helper-backend:local
    container_name: backend
    ports:
      - 1337:8000
  frontend:
    image: anno-1800-explorer-helper-frontend:local
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 4042:80

